apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9216"
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongodb-data
        envFrom:
          - secretRef:
              name: mongodb-secret
      - name: mongodbexporter
        image: harrisonlima/mongo_exporter
        resources: {}
        ports:
          - containerPort: 9216
        volumeMounts:
          - mountPath: /data/db
            name: mongodb-data
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@localhost:27017
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: digitalocean-pvc     

          